### ISSUE TITLE
los epub no funcionan

### ISSUE THREAD

**Issue by Chipipablo** [s-nt-s/GSI#1]
Buenas,
Parece ser que los ficheros epub no están funcionando correctamente.

**Comment by s-nt-s** [comment]
¿Puedes dar más detalles de cual es el problema? A mi me funcionan correctamente.

**Comment by Chipipablo** [comment]
Pues al abrirlos, tanto en el pc como en el ebook, se abren, pero no muestran el contenido, pongo captura.
Gracias
![image](https://user-images.githubusercontent.com/8601512/55675196-30aaab80-58bf-11e9-9b67-5d19b64f1e58.png)

**Comment by s-nt-s** [comment]
¿Que eReader tienes?

No uso windows, pero ¿seguro que se pueden abrir epubs en internet explorer?
En cualquier caso, puedes probar con [calibre](https://calibre-ebook.com/) que es multiplataforma y con muchos eReader que lo necesitan hace la conversión que haga falta para que se lea bien.

**Comment by Chipipablo** [comment]
Finalmente lo he reconvertido con Calibre, ¡muchas gracias!
¿Es posible que tenga algo que ver con la versión de epub?, lo que he hecho es una conversión a la versión 2, tras esto me ha funcionado correctamente.

**Comment by s-nt-s** [comment]
Puede ser, pero el eReader que yo uso es un Kobo Mini de 2012; si va en eso debería ir en casi cualquier cosa.

**Comment by Chipipablo** [comment]
Yo tengo un Woxter Scriba 195. No sé, me parece raro que no fuera, ni en el ebook ni en el lector del pc (yo tampoco sabía que el navegador lo leyera, pero es la aplicación por defecto). Tras la reconversión se abre en ambos sitios.
